Removing redundant sharp sign
ashleygwilliams/assert_approx_eq pull request #9
Opened 2017-04-15 12:43 UTC by afshinm

2017-04-15 18:44 UTC, ashleygwilliams requested changes
thank you so much for this! one little nit and then i'll merge and publish a patch version! :)

2017-04-15 18:44 UTC, ashleygwilliams commented on src/lib.rs
> +//  extern crate assert_approx_eq;
could you make this a `///`? thanks!

2017-04-18 13:15 UTC, afshinm commented on src/lib.rs
> +//  extern crate assert_approx_eq;
ops, sorry. sure.

2017-04-18 13:16 UTC, afshinm commented
done 👍

2017-04-18 13:45 UTC, ashleygwilliams requested changes

2017-04-18 13:45 UTC, ashleygwilliams commented on src/lib.rs
> +///  extern crate assert_approx_eq;
sorry to be nitpicky but it appears there is a space here! mind removing that as well?

2017-04-18 19:33 UTC, afshinm commented
ah sorry about that. done.

2017-08-21 21:20 UTC, afshinm commented
ping!

2017-10-24 17:17 UTC, closed without merging